name: call git api
on: 
   push:
        branches: main

jobs:
    call-api:
        runs-on: ubuntu-latest
        steps: 
            - uses: octokit/request-action@v2.1.0 
              id: codelanguages
              with:
                route: GET /repos/{owner}/{repo}/languages
                owner: omkarkakade2017
                repo: WolfiJavaDemo1
              env:
                GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
            - run: "echo data found : '${{steps.codelanguages.outputs.data}}'"
              
    
