name: call git api
on: 
   workflow_dispatch:
      inputs:
         name: 
            description: Enter Repo Name
            required: true
jobs:
    call-api:
        runs-on: ubuntu-latest
        steps: 
            - uses: octokit/request-action@v2.1.0 
              id: codelanguages
              with:
                route: GET /repos/{owner}/{repo}/languages
                owner: omkarkakade2017
                repo: ${{github.event.inputs.name}}
                mediaType: | # The | download
                   format: raw
              env:
                GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
            - run: "echo data found : '${{steps.codelanguages.outputs.data}}'"

            - name: Write data to JSON file
              run: |
                  echo data found : '${{steps.codelanguages.outputs.data}}' > data.json
            
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v4
              with:
                     name: data
                     path: data.json
                     retention-days: 1

            - name: Download Generated file
              uses: actions/download-artifact@v4
              

            - name: list files
              run: ls -R
              
    
